import { CheckCircleOutline, Refresh, WarningAmberOutlined } from '@mui/icons-material';

const titleCase = (value) => value === 'investigating' ? 'In Progress' : String(value || '').replace(/_/g, ' ').replace(/\b\w/g, (letter) => letter.toUpperCase());
const Heading = ({ eyebrow, title, description, action }) => <div className="mb-5 flex flex-col gap-3 border-b border-slate-200/80 pb-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="dashboard-eyebrow">{eyebrow}</p><h2 className="mt-2 text-xl font-black tracking-tight text-[#0b1f3a] sm:text-2xl">{title}</h2>{description && <span className="mt-1 block max-w-2xl text-sm leading-6 text-slate-500">{description}</span>}</div>{action && <div className="flex flex-wrap items-center gap-2">{action}</div>}</div>;
const EmptyState = ({ title, message }) => <div className="flex min-h-[220px] flex-col items-center justify-center rounded-3xl border border-dashed border-slate-300 bg-white p-8 text-center shadow-sm"><CheckCircleOutline className="mb-3 rounded-2xl bg-cyan-50 p-3 text-[54px] text-cyan-700 ring-1 ring-cyan-100" /><h3 className="text-lg font-black text-[#0b1f3a]">{title}</h3><p className="mt-2 max-w-md text-sm leading-6 text-slate-500">{message}</p></div>;

export function AnalyticsPage({ analytics, loading, error, onRefresh }) {
  const data = analytics || {};
  const severity = data.by_severity || {};
  const status = data.by_status || {};
  return <div className="space-y-8"><Heading eyebrow="Decision support" title="Incident analytics" description="Live aggregates from the incident service." action={<button type="button" className="dashboard-button" onClick={onRefresh}><Refresh className="text-[18px]" /> Refresh</button>} />{error && <div className="dashboard-error" role="alert">{error}</div>}{loading ? <div className="inline-loading">Loading analytics...</div> : <><div className="grid grid-cols-1 gap-5 sm:grid-cols-2 xl:grid-cols-5"><Metric label="Total incidents" value={data.total_incidents || 0} /><Metric label="Critical" value={severity.critical || 0} tone="red" /><Metric label="High" value={severity.high || 0} tone="amber" /><Metric label="Resolved" value={(status.resolved || 0) + (status.closed || 0)} tone="teal" /><Metric label="Active" value={['reported', 'investigating', 'dispatched', 'on_scene'].reduce((sum, key) => sum + (status[key] || 0), 0)} tone="slate" /></div><div className="grid gap-6 lg:grid-cols-2"><section className="dashboard-panel border-slate-200/80 bg-white shadow-[0_8px_24px_rgba(15,23,42,0.04)]"><h3 className="text-lg font-black text-[#0b1f3a]">By severity</h3><div className="mt-5 space-y-4">{Object.entries(severity).map(([key, value]) => <Bar key={key} label={titleCase(key)} value={value} total={data.total_incidents} />)}</div></section><section className="dashboard-panel border-slate-200/80 bg-white shadow-[0_8px_24px_rgba(15,23,42,0.04)]"><h3 className="text-lg font-black text-[#0b1f3a]">By status</h3><div className="mt-5 grid gap-3 sm:grid-cols-2">{Object.entries(status).map(([key, value]) => <div key={key} className="rounded-2xl border border-slate-200 bg-slate-50 p-4 transition hover:border-cyan-200 hover:bg-cyan-50/30"><p className="text-xs font-black uppercase tracking-wider text-slate-500">{titleCase(key)}</p><p className="mt-1 text-2xl font-black text-[#0b1f3a]">{value}</p></div>)}</div></section></div></>}</div>;
}

export function ResponsesPage({ responses, loading, error, onRefresh }) {
  return <div className="space-y-8"><Heading eyebrow="Field coordination" title="Response management" description="Assignments and response status from the response service." action={<button type="button" className="dashboard-button" onClick={onRefresh}><Refresh className="text-[18px]" /> Refresh</button>} />{error && <div className="dashboard-error" role="alert">{error}</div>}{loading ? <div className="inline-loading">Loading responses...</div> : responses.length ? <div className="dashboard-panel overflow-x-auto border-slate-200/80 bg-white shadow-[0_8px_24px_rgba(15,23,42,0.04)]"><table className="dashboard-table"><thead><tr><th>Incident</th><th>Responder</th><th>Status</th><th>Response time</th><th>Assigned</th></tr></thead><tbody>{responses.map((response) => <tr key={response.response_id}><td className="font-bold">{titleCase(response.incident?.type || 'Incident')}<span className="block text-xs font-normal text-slate-500">{response.incident?.location_name || 'Campus'}</span></td><td>{response.responder?.name || response.responder_id}</td><td><span className="status-badge">{titleCase(response.status)}</span></td><td>{response.response_time_seconds == null ? 'Pending' : `${response.response_time_seconds}s`}</td><td>{response.created_at ? new Date(response.created_at).toLocaleString() : 'Unknown'}</td></tr>)}</tbody></table></div> : <EmptyState title="No responses" message="No response assignments are currently available." />}</div>;
}

export function AlertsZonesPage({ alerts, zones, loading, error, onRefresh, onReadAlert, canManage }) {
  return <div className="space-y-8"><Heading eyebrow="Communications and coverage" title="Alerts and zones" description={canManage ? 'Review alerts and active campus zones. Alert actions are limited to supported operations.' : 'Review alerts and active campus zones.'} action={<button type="button" className="dashboard-button" onClick={onRefresh}><Refresh className="text-[18px]" /> Refresh</button>} />{error && <div className="dashboard-error" role="alert">{error}</div>}{loading ? <div className="inline-loading">Loading alerts and zones...</div> : <div className="grid gap-6 xl:grid-cols-2"><section className="dashboard-panel border-slate-200/80 bg-white shadow-[0_8px_24px_rgba(15,23,42,0.04)]"><h3 className="text-lg font-black text-[#0b1f3a]">Alerts</h3>{alerts.length ? <div className="mt-4 space-y-3">{alerts.map((alert) => <article key={alert.alert_id} className="rounded-2xl border border-slate-200 bg-slate-50 p-4 transition hover:border-cyan-200 hover:bg-cyan-50/30"><div className="flex gap-3"><WarningAmberOutlined className="text-amber-600" /><div className="min-w-0 flex-1"><div className="flex flex-wrap items-start justify-between gap-2"><h4 className="font-black text-[#0b1f3a]">{alert.title || titleCase(alert.type)}</h4>{canManage && !alert.is_read && <button type="button" className="table-action" onClick={() => onReadAlert(alert.alert_id)}>Mark read</button>}</div><p className="mt-1 text-sm text-slate-600">{alert.message || 'No additional details.'}</p><p className="mt-2 text-xs text-slate-500">{alert.sent_at ? new Date(alert.sent_at).toLocaleString() : 'Unscheduled'}</p></div></div></article>)}</div> : <div className="mt-4"><EmptyState title="No alerts" message="There are no alerts to display." /></div>}</section><section className="dashboard-panel border-slate-200/80 bg-white shadow-[0_8px_24px_rgba(15,23,42,0.04)]"><h3 className="text-lg font-black text-[#0b1f3a]">Active zones</h3>{zones.length ? <div className="mt-4 grid gap-3 sm:grid-cols-2">{zones.map((zone) => <article key={zone.zone_id} className="rounded-2xl border border-slate-200 bg-slate-50 p-4 transition hover:border-cyan-200 hover:bg-cyan-50/30"><h4 className="font-black text-[#0b1f3a]">{zone.name}</h4><p className="mt-1 text-sm text-slate-600">{zone.description || 'No description provided.'}</p><p className="mt-3 text-xs font-bold text-slate-500">Radius: {zone.radius || 'Unknown'}m</p></article>)}</div> : <div className="mt-4"><EmptyState title="No active zones" message="No active zones are configured in the backend." /></div>}<p className="mt-4 text-xs text-slate-500">Zone creation and editing are unavailable because the current backend exposes read-only zone operations.</p></section></div>}</div>;
}

function Metric({ label, value, tone = 'slate' }) { const colors = { slate: 'bg-slate-100 text-slate-700 ring-slate-200', amber: 'bg-amber-50 text-amber-700 ring-amber-200', red: 'bg-red-50 text-red-700 ring-red-200', teal: 'bg-cyan-50 text-cyan-700 ring-cyan-200' }; return <article className="dashboard-panel border-slate-200/80 bg-white shadow-[0_8px_24px_rgba(15,23,42,0.04)]"><span className={`inline-flex rounded-xl px-3 py-1 text-[10px] font-black uppercase tracking-wider ring-1 ${colors[tone]}`}>Live</span><p className="mt-4 text-xs font-black uppercase tracking-wider text-slate-500">{label}</p><p className="mt-1 text-3xl font-black tracking-tight text-[#0b1f3a]">{value}</p></article>; }
function Bar({ label, value, total }) { const width = total ? Math.min(100, (value / total) * 100) : 0; return <div><div className="flex justify-between text-sm font-bold text-slate-700"><span>{label}</span><span className="text-[#0b1f3a]">{value}</span></div><div className="mt-2 h-2 rounded-full bg-slate-100"><div className="h-2 rounded-full bg-cyan-500 transition-all" style={{ width: `${width}%` }} /></div></div>; }

