import { useEffect, useSyncExternalStore } from 'react';

const STORAGE_KEY = 'campussecure-language';
const listeners = new Set();

const readLanguage = () => localStorage.getItem(STORAGE_KEY) === 'am' ? 'am' : 'en';

const notifyLanguageChange = () => {
  listeners.forEach((listener) => listener());
};

if (typeof window !== 'undefined') {
  window.addEventListener('storage', (event) => {
    if (event.key === STORAGE_KEY) notifyLanguageChange();
  });
}

export function setLanguage(language) {
  const nextLanguage = language === 'am' ? 'am' : 'en';
  localStorage.setItem(STORAGE_KEY, nextLanguage);
  document.documentElement.lang = nextLanguage;
  notifyLanguageChange();
}

export function useLanguage() {
  const language = useSyncExternalStore(
    (listener) => {
      listeners.add(listener);
      return () => listeners.delete(listener);
    },
    readLanguage,
    () => 'en'
  );

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  return [language, setLanguage];
}

export function useTranslate() {
  const [language] = useLanguage();
  return (text) => translateDashboardText(text, language);
}

const dashboardAmharic = {
  'Overview': 'አጠቃላይ እይታ',
  'Active incidents': 'ንቁ ክስተቶች',
  'Incident history': 'የክስተት ታሪክ',
  'Emergency center': 'የአደጋ ጊዜ ማዕከል',
  'Live map': 'ቀጥታ ካርታ',
  'Live campus map': 'የግቢ ቀጥታ ካርታ',
  'SOS / Emergency': 'SOS / አደጋ ጊዜ',
  'Evidence': 'ማስረጃ',
  'Security officers': 'የደህንነት ኦፊሰሮች',
  'User management': 'የተጠቃሚ አስተዳደር',
  'Analytics': 'ትንታኔ',
  'Incident analytics': 'የክስተት ትንታኔ',
  'Responses': 'ምላሾች',
  'Response management': 'የምላሽ አስተዳደር',
  'Alerts and zones': 'ማንቂያዎች እና ዞኖች',
  'Announcements': 'ማስታወቂያዎች',
  'SMS Broadcast': 'የSMS ስርጭት',
  'Campus locations': 'የግቢ ቦታዎች',
  'Notifications': 'ማሳወቂያዎች',
  'Audit logs': 'የኦዲት መዝገቦች',
  'Content management': 'የይዘት አስተዳደር',
  'System settings': 'የስርዓት ቅንብሮች',
  'Log out': 'ውጣ',
  'Search': 'ፈልግ',
  'Filters': 'ማጣሪያዎች',
  'Workspace': 'የሥራ ቦታ',
  'Security Operations Center': 'የደህንነት ኦፕሬሽን ማዕከል',
  'Campus security': 'የግቢ ደህንነት',
  'Campus security / overview': 'የግቢ ደህንነት / አጠቃላይ እይታ',
  'Live notifications': 'ቀጥታ ማሳወቂያዎች',
  'unread': 'ያልተነበቡ',
  'No new notifications': 'አዲስ ማሳወቂያዎች የሉም',
  'Clearing...': 'በማጽዳት ላይ...',
  'Clear history': 'ታሪክን አጽዳ',
  'Live feed': 'ቀጥታ ምግብ',
  'Close navigation': 'አሰሳን ዝጋ',
  'Open navigation': 'አሰሳን ክፈት',
  'Dashboard': 'ዳሽቦርድ',
  'Campus overview': 'የግቢ አጠቃላይ እይታ',
  'Campus Security Operations': 'የግቢ ደህንነት ኦፕሬሽኖች',
  'Total Incidents': 'ጠቅላላ ክስተቶች',
  'Active Incidents': 'ንቁ ክስተቶች',
  'Security Officers': 'የደህንነት ኦፊሰሮች',
  'Live count unavailable': 'የቀጥታ ቆጠራ አይገኝም',
  'Your campus security overview and response workspace.': 'የግቢ ደህንነት አጠቃላይ እይታዎ እና የምላሽ የሥራ ቦታዎ።',
  'Review the incident queue': 'የክስተት ወረፋውን ይመልከቱ',
  'Open Live Map': 'ቀጥታ ካርታን ክፈት',
  'View campus activity': 'የግቢ እንቅስቃሴን ይመልከቱ',
  'Response queue': 'የምላሽ ወረፋ',
  'Recent / Active Incidents': 'የቅርብ ጊዜ / ንቁ ክስተቶች',
  'View incidents': 'ክስተቶችን ይመልከቱ',
  'Incident information is unavailable': 'የክስተት መረጃ አይገኝም',
  'Incident records are not provided to this dashboard view.': 'የክስተት መዝገቦች በዚህ የዳሽቦርድ እይታ አልቀረቡም።',
  'Updates': 'ዝማኔዎች',
  'Notifications & Activity': 'ማሳወቂያዎች እና እንቅስቃሴ',
  'No activity to display': 'የሚታይ እንቅስቃሴ የለም',
  'New notifications remain available from the header.': 'አዲስ ማሳወቂያዎች ከራስጌው ላይ ይገኛሉ።',
  'Emergency Center': 'የአደጋ ጊዜ ማዕከል',
  'Open emergency response tools': 'የአደጋ ጊዜ ምላሽ መሳሪያዎችን ክፈት',
  'View the officer workspace': 'የኦፊሰር የሥራ ቦታን ይመልከቱ',
  'Reports & Analytics': 'ሪፖርቶች እና ትንታኔ',
  'Open incident reporting': 'የክስተት ሪፖርትን ክፈት',
  'Campus Security Command Center': 'የግቢ ደህንነት ትዕዛዝ ማዕከል',
  'Quick actions': 'ፈጣን እርምጃዎች',
  'Manage incidents': 'ክስተቶችን አስተዳድር',
  'Open live map': 'ቀጥታ ካርታን ክፈት',
  'Officer status': 'የኦፊሰር ሁኔታ',
  'Send SMS': 'SMS ላክ',
  'Report incident': 'ክስተት ሪፖርት አድርግ',
  'Export incidents': 'ክስተቶችን ላክ',
  'View analytics': 'ትንታኔን አሳይ',
  'ML insights': 'የML ግንዛቤዎች',
  'View notifications': 'ማሳወቂያዎችን አሳይ',
  'Security status': 'የደህንነት ሁኔታ',
  'Total incidents': 'ጠቅላላ ክስተቶች',
  'Critical / SOS': 'አስቸኳይ / SOS',
  'Activity': 'እንቅስቃሴ',
  'Live operations': 'ቀጥታ ኦፕሬሽኖች',
  'Campus activity': 'የግቢ እንቅስቃሴ',
  'Current incident and response metrics at a glance.': 'የአሁኑን የክስተትና የምላሽ መለኪያዎች በአጭሩ ይመልከቱ።',
  'Live data': 'ቀጥታ መረጃ',
  'Incident operations': 'የክስተት ኦፕሬሽኖች',
  'Refresh': 'አድስ',
  'Send SOS alert': 'የSOS ማንቂያ ላክ',
  'Security operations center': 'የደህንነት ኦፕሬሽን ማዕከል',
  'Live incident, response, and system activity from the campus security service.': 'ከግቢው ደህንነት አገልግሎት የቀጥታ ክስተት፣ ምላሽ እና የስርዓት እንቅስቃሴ።',
  'Operational awareness': 'የኦፕሬሽን ግንዛቤ',
  'Monitor campus safety activity, keep response teams aligned, and preserve situational visibility across live incidents and active coverage zones.': 'የግቢ ደህንነት እንቅስቃሴን ይከታተሉ፣ የምላሽ ቡድኖችን ያቀናጁ እና በቀጥታ ክስተቶችና ንቁ የክትትል ዞኖች ላይ ያለውን ሁኔታ ይመልከቱ።',
  'Response readiness': 'የምላሽ ዝግጁነት',
  'Critical incidents and officer assignments are monitored in real time.': 'አስቸኳይ ክስተቶችና የኦፊሰር ምደባዎች በቅጽበት ይከታተላሉ።',
  'Loading incidents...': 'ክስተቶችን በመጫን ላይ...',
  'Loading...': 'በመጫን ላይ...',
  'No incidents found': 'ክስተቶች አልተገኙም',
  'There are no records matching the current filters or the queue is clear.': 'ከአሁኑ ማጣሪያዎች ጋር የሚዛመድ መዝገብ የለም ወይም ወረፋው ባዶ ነው።',
  'Incident': 'ክስተት',
  'Reporter': 'ሪፖርት አድራጊ',
  'Priority': 'ቅድሚያ',
  'Severity': 'ክብደት',
  'Status': 'ሁኔታ',
  'Location': 'ቦታ',
  'Date': 'ቀን',
  'Actions': 'እርምጃዎች',
  'View': 'አሳይ',
  'Assign': 'መድብ',
  'Update': 'አዘምን',
  'Save': 'አስቀምጥ',
  'Cancel': 'ሰርዝ',
  'Submit': 'አስገባ',
  'Name': 'ስም',
  'Email': 'ኢሜይል',
  'Phone Number': 'ስልክ ቁጥር',
  'Role': 'ሚና',
  'Description': 'መግለጫ',
  'Type': 'አይነት',
  'Created': 'የተፈጠረበት',
  'Search action or resource': 'እርምጃ ወይም ምንጭ ፈልግ',
  'From': 'ከ',
  'To': 'እስከ',
  'Retry': 'እንደገና ሞክር',
  'Nothing to display.': 'የሚታይ ነገር የለም።',
  'Read': 'ተነብቧል',
  'Unread': 'አልተነበበም',
  'Pending': 'በመጠባበቅ ላይ',
  'Resolved': 'ተፈትቷል',
  'Closed': 'ተዘግቷል',
  'In Progress': 'በሂደት ላይ',
  'High': 'ከፍተኛ',
  'Medium': 'መካከለኛ',
  'Low': 'ዝቅተኛ',
  'Critical': 'አስቸኳይ',
  'Available': 'ዝግጁ',
  'Offline': 'ከመስመር ውጭ',
  'Responding': 'ምላሽ በመስጠት ላይ',
  'Completed': 'ተጠናቋል',
  'Processing...': 'በማስኬድ ላይ...',
  'Apply filters': 'ማጣሪያዎችን ተግብር',
  'Clear filters': 'ማጣሪያዎችን አጽዳ',
  'Home': 'መነሻ',
  'About': 'ስለ እኛ',
  'Features': 'ባህሪያት',
  'Contact': 'ያግኙን',
  'English': 'English',
  'Amharic': 'አማርኛ',
  'Language': 'ቋንቋ',
  'Enter your phone number': 'ስልክ ቁጥርዎን ያስገቡ',
  'Continue with Google': 'በGoogle ይቀጥሉ',
  'Connecting...': 'በመገናኘት ላይ...',
  'OR': 'ወይም',
  'Welcome back': 'እንኳን ደህና መጡ',
  'Secure sign in': 'ደህንነቱ የተጠበቀ መግቢያ',
  'Use your campus account to continue.': 'ለመቀጠል የግቢ መለያዎን ይጠቀሙ።',
  'Campus email': 'የግቢ ኢሜይል',
  'Password': 'የይለፍ ቃል',
  'Forgot Password?': 'የይለፍ ቃል ረሱ?',
  'Sign in to dashboard': 'ወደ ዳሽቦርድ ይግቡ',
  'Please wait...': 'እባክዎ ይጠብቁ...',
  'New to CampusSecure?': 'CampusSecureን አዲስ ነዎት?',
  'Create an account': 'መለያ ይፍጠሩ',
  'Back to CampusSecure': 'ወደ CampusSecure ይመለሱ',
  'Secure access for authorized campus members.': 'ለተፈቀደላቸው የግቢ አባላት ደህንነቱ የተጠበቀ መዳረሻ።',
  'Create your account': 'መለያዎን ይፍጠሩ',
  'Join CampusSecure.': 'CampusSecureን ይቀላቀሉ።',
  'Public registration is available for students, faculty, and staff.': 'ለተማሪዎች፣ መምህራን እና ሠራተኞች የህዝብ ምዝገባ ይገኛል።',
  'Full name': 'ሙሉ ስም',
  'Your full name': 'ሙሉ ስምዎን ያስገቡ',
  'At least 8 characters': 'ቢያንስ 8 ቁምፊዎች',
  'Confirm password': 'የይለፍ ቃልን ያረጋግጡ',
  'Repeat your password': 'የይለፍ ቃልዎን ይድገሙ',
  'Your role': 'ሚናዎ',
  'Student': 'ተማሪ',
  'Faculty': 'መምህር',
  'Staff': 'ሠራተኛ',
  'Create account': 'መለያ ይፍጠሩ',
  'Already have an account?': 'መለያ አለዎት?',
  'Sign in': 'ግባ',
  'Hide password': 'የይለፍ ቃልን ደብቅ',
  'Show password': 'የይለፍ ቃልን አሳይ',
  'Officer': 'ኦፊሰር',
  'Updated': 'የተዘመነ',
  'Action': 'እርምጃ',
  'Assign officer': 'ኦፊሰር መድብ',
  'Assigning...': 'በመመደብ ላይ...',
  'Location unavailable': 'ቦታ አይገኝም',
  'No description provided': 'መግለጫ አልተሰጠም',
  'Anonymous': 'ስም የማይገለጽ',
  'Campus member': 'የግቢ አባል',
  'Reported': 'ሪፖርት ተደርጓል',
  'Investigating': 'በምርመራ ላይ',
  'Dispatched': 'ተልኳል',
  'On Scene': 'ቦታው ላይ ነው',
  'Profile': 'መገለጫ',
  'Content Management': 'የይዘት አስተዳደር',
  'System Settings': 'የስርዓት ቅንብሮች',
  'Incidents': 'ክስተቶች',
  'History': 'ታሪክ',
  'Map': 'ካርታ',
  'SOS': 'SOS',
  'Users': 'ተጠቃሚዎች',
  'Zones': 'ዞኖች',
  'Locations': 'ቦታዎች',
  'Emergency': 'አደጋ ጊዜ',
  'AuditLogs': 'የኦዲት መዝገቦች',
  'Content': 'ይዘት',
  'Settings': 'ቅንብሮች',
  'Live': 'ቀጥታ',
  'Change status for': 'ሁኔታን ቀይር፦',
  'Assign officer for': 'ኦፊሰር መድብ፦',
  'Unassigned': 'አልተመደበም',
  'Dashboard data issue': 'የዳሽቦርድ መረጃ ችግር',
  'Loading analytics...': 'ትንታኔን በመጫን ላይ...',
  'Loading responses...': 'ምላሾችን በመጫን ላይ...',
  'Loading alerts and zones...': 'ማንቂያዎችን እና ዞኖችን በመጫን ላይ...',
  'Loading map data...': 'የካርታ መረጃን በመጫን ላይ...',
  'Loading users...': 'ተጠቃሚዎችን በመጫን ላይ...',
  'Loading officers...': 'ኦፊሰሮችን በመጫን ላይ...',
  'Decision support': 'የውሳኔ ድጋፍ',
  'Live aggregates from the incident service.': 'ከክስተት አገልግሎቱ የቀጥታ ድምር መረጃ።',
  'By severity': 'በክብደት',
  'By status': 'በሁኔታ',
  'Field coordination': 'የመስክ ቅንጅት',
  'Assignments and response status from the response service.': 'ከምላሽ አገልግሎቱ የተሰጡ ምደባዎችና የምላሽ ሁኔታ።',
  'Responder': 'ምላሽ ሰጪ',
  'Response time': 'የምላሽ ጊዜ',
  'Assigned': 'ተመድቧል',
  'No responses': 'ምላሾች የሉም',
  'No response assignments are currently available.': 'በአሁኑ ጊዜ ምንም የምላሽ ምደባ የለም።',
  'Communications and coverage': 'ግንኙነቶች እና ሽፋን',
  'Review alerts and active campus zones.': 'ማንቂያዎችንና ንቁ የግቢ ዞኖችን ይመልከቱ።',
  'Alerts': 'ማንቂያዎች',
  'Active zones': 'ንቁ ዞኖች',
  'Mark read': 'እንደተነበበ ምልክት አድርግ',
  'No additional details.': 'ተጨማሪ ዝርዝር የለም።',
  'No alerts': 'ማንቂያዎች የሉም',
  'There are no alerts to display.': 'የሚታዩ ማንቂያዎች የሉም።',
  'No active zones': 'ንቁ ዞኖች የሉም',
  'No active zones are configured in the backend.': 'በጀርባ ስርዓቱ ምንም ንቁ ዞን አልተዋቀረም።',
  'Notification': 'ማሳወቂያ',
  'Resource': 'ምንጭ',
  'Mark all as read': 'ሁሉንም እንደተነበቡ ምልክት አድርግ',
  'Open': 'ክፈት',
  'Administrative awareness': 'የአስተዳደር ግንዛቤ',
  'Review server-generated incident, SOS, assignment, and system notifications.': 'በሰርቨር የተፈጠሩ የክስተት፣ SOS፣ የምደባ እና የስርዓት ማሳወቂያዎችን ይመልከቱ።',
  'Accountability': 'ተጠያቂነት',
  'Server-generated records of security-sensitive administrative actions.': 'በደህንነት ላይ የሚመሰረቱ የአስተዳደር እርምጃዎች በሰርቨር የተፈጠሩ መዝገቦች።',
  'Administrator': 'አስተዳዳሪ',
  'Details': 'ዝርዝሮች',
  'System': 'ስርዓት',
  'No details': 'ዝርዝር የለም',
  'Configuration': 'ውቅር',
  'Manage effective operational settings. Provider secrets remain server-side and are never returned.': 'የኦፕሬሽን ቅንብሮችን ያስተዳድሩ። የአቅራቢ ሚስጥሮች በሰርቨር ላይ ይቆያሉ እና አይመለሱም።',
  'Settings saved.': 'ቅንብሮች ተቀምጠዋል።',
  'Save settings': 'ቅንብሮችን አስቀምጥ',
  'Reports currently in the response queue.': 'በአሁኑ ጊዜ በምላሽ ወረፋ ውስጥ ያሉ ሪፖርቶች።',
  'All incident records returned by the backend.': 'በጀርባ ስርዓቱ የተመለሱ ሁሉም የክስተት መዝገቦች።',
  'SOS and critical incidents': 'SOS እና አስቸኳይ ክስተቶች',
  'Critical reports requiring rapid review.': 'ፈጣን ግምገማ የሚፈልጉ አስቸኳይ ሪፖርቶች።',
  'Geospatial response': 'በጂኦግራፊያዊ ቦታ ላይ የተመሠረተ ምላሽ',
  'Campus places, security zones, current officer locations, and incident coordinates.': 'የግቢ ቦታዎች፣ የደህንነት ዞኖች፣ የኦፊሰሮች ወቅታዊ ቦታዎች እና የክስተት መጋጠሚያዎች።',
  'Back to incidents': 'ወደ ክስተቶች ተመለስ',
  'Attached photos': 'የተያያዙ ፎቶዎች',
  'No evidence attached': 'ማስረጃ አልተያያዘም',
  'This incident has no uploaded photos.': 'ለዚህ ክስተት የተሰቀሉ ፎቶዎች የሉም።',
  'Incident not found': 'ክስተቱ አልተገኘም',
  'The requested incident is unavailable.': 'የተጠየቀው ክስተት አይገኝም።',
  'Evidence review': 'የማስረጃ ግምገማ',
  'Incident evidence': 'የክስተት ማስረጃ',
  'Uploaded photos associated with incident records.': 'ከክስተት መዝገቦች ጋር የተያያዙ የተሰቀሉ ፎቶዎች።',
  'No evidence available': 'ማስረጃ አይገኝም',
  'Photo evidence will appear here when incidents include uploads.': 'ክስተቶች ፎቶዎችን ሲያካትቱ የፎቶ ማስረጃ እዚህ ይታያል።',
  'Access and people': 'መዳረሻ እና ሰዎች',
  'Campus accounts returned by the security service.': 'በደህንነት አገልግሎቱ የተመለሱ የግቢ መለያዎች።',
  'notifications': 'ማሳወቂያዎች',
  'incident': 'ክስተት',
  'Reported': 'ሪፖርት ተደርጓል',
  'In Progress': 'በሂደት ላይ',
  'Dispatched': 'ተልኳል',
  'On Scene': 'ቦታው ላይ',
  'Resolved': 'ተፈትቷል',
  'Closed': 'ተዘግቷል',
};

export function translateDashboardText(text, language) {
  if (language !== 'am' || typeof text !== 'string') return text;
  return dashboardAmharic[text] || text;
}
